In [17]:
import tensorflow as tf

In [18]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [19]:
# check the number of the dimensions
scalar.ndim

0

In [20]:
#create vector
vector = tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [21]:
#check the dimension of our vector
vector.ndim

1

In [22]:
#create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [23]:
matrix.ndim

2

In [24]:
# create another matrix
another_matrix = tf.constant([[10.,7.],[7.,10.],[7.,11.]],dtype=tf.float16) #specify the dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 7., 11.]], dtype=float16)>

In [25]:
another_matrix.ndim

2

In [26]:
# lets create a tensor
tensor = tf.constant([[[1, 2, 3,],[4,5,6]],[[7,8,9],[10, 11, 12]],[[13,14,15],[15,16,17]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [15, 16, 17]]], dtype=int32)>

In [27]:
tensor.ndim

3

what we've created so far:

* scaler : a single number
* vector : a number with direction (e.g. wind speed and direction)
* matrix : a 2-dimensional array of numbers
* Tensor : an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensor with tf.variable


In [28]:
changable_tensor = tf.Variable([1,2])
unchangable_tensor = tf.constant([1,2])
changable_tensor,unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [29]:
# lets try change one of the elements in our changable
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 2], dtype=int32)>

### creating random tensors

Random tensors are tensors of some abitray size which contain random numbers

In [30]:
# create two random (but the smae) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in a tensor

In [31]:
#shuffle a tensor (valuable for when to shuffle your data so the inherent order does'nt effect learning)
not_shuffled = tf.constant([[10, 7],[3,4],[2,5]])

tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [32]:
tf.ones([10,7])


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [33]:
#create a tensor of all zeroes
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into Tensors

the main difference between Numpy arrays and Tensorflow tensors is that tensors can be run on gpu (much more faster gor numerical computing)

In [34]:
# you can also turn numpy arrays into Tensors
import numpy as np

numpy_a = np.arange(1,25 ,dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [35]:
a = tf.constant(numpy_a, shape=(2,3,4)) # 2*3*4 = 24
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors

when dealing with tensors you probably want to be aware of the following attributes:
* shape
* Rank
* Axis or dimensions
* Size

In [36]:
# create a Rank 4 for tensor
rank_4 = tf.zeros(shape=([2,3,4,5]))
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
rank_4.shape,rank_4.ndim,tf.size(rank_4),

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [38]:
# get various attributes of our tensor
print('Datatype of every element:',rank_4.dtype)
print('number of dimension:',rank_4.ndim)
print('shape of tensor:',rank_4.shape)
print('Elements along the 0 axis:',rank_4.shape[0])
print('Element along the last axis:',rank_4.shape[-1])
print('total number of elements in our tensor:',tf.size(rank_4).numpy())

Datatype of every element: <dtype: 'float32'>
number of dimension: 4
shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Element along the last axis: 5
total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [39]:
# Get the first 2 element of each dimension
rank_4[:2,:3,:2,:2]

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [40]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [41]:
# Get the first element from each dimension from each index except final one
rank_4[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [42]:
# Create a rank 2 tensor (2 dimensions)
rank_2 = tf.constant([[1,2],[3,4]])
rank_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [43]:
# Get the last item of each of our rank 2 tensor
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [44]:
# Add in extra dimention to our rank 2 tensor
rank_3 = rank_2[...,tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [45]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2, axis=-1) # '-1' means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [46]:
tf.expand_dims(rank_2, axis=0) #expand the zero axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

In [47]:
# you can add value to the tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [48]:
# multiplication 
tensor * 10
#subtraction
tensor - 10



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [49]:
# we can use the tensorflow build-in fuction too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication

in machine learning, matrix multiplication is the most commen tensor operations

In [50]:
# matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [51]:
# Matrix multiplication with python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [52]:
#Lets change the shape
y = tf.constant([[1,2],[4,5],[4,5]])

tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [5, 4, 5]], dtype=int32)>

In [53]:
tensor @ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[45, 48, 75],
       [23, 22, 32]], dtype=int32)>

In [54]:
# can do the same with transpose
tf.transpose(y), tf.reshape(y, shape=(2,3)) # change the axis

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 4, 4],
        [2, 5, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [5, 4, 5]], dtype=int32)>)

In [55]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tensor, tf.transpose(y))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[24, 75, 75],
       [11, 32, 32]], dtype=int32)>

** The Dot product **

Matrix multiplication is also referred to as the dot product.

You can perform matri multiplication using:
* `tf.matmul()`
* `tf.tesnordot()`

In [56]:
#Perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tensor, tf.transpose(y), axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[24, 75, 75],
       [11, 32, 32]], dtype=int32)>

In [57]:
# Perform matrix multiplication between x and y (transposed)
tf.matmul(tensor, tf.transpose(y))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[24, 75, 75],
       [11, 32, 32]], dtype=int32)>

In [58]:
# check the values of y, reshape y and transposed y
print('normal y:')
print(y,'')

print('y reshape:')
print(tf.reshape(y, (2,3)),'')

print('y transposed:')
print(tf.transpose(y))

normal y:
tf.Tensor(
[[1 2]
 [4 5]
 [4 5]], shape=(3, 2), dtype=int32) 
y reshape:
tf.Tensor(
[[1 2 4]
 [5 4 5]], shape=(2, 3), dtype=int32) 
y transposed:
tf.Tensor(
[[1 4 4]
 [2 5 5]], shape=(2, 3), dtype=int32)


Generally,when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose(rather than reshape) one of the tensors to get satisify the matrix multiplication rules

### changing the datatype of a tensor

In [59]:
# create a new tensor with default datatype (float32)
b = tf.constant([1.7,7.4])
b.dtype

tf.float32

In [60]:
#Change from float32 to float16
b = tf.cast(b, dtype=tf.float16)
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Aggregating tensors

Aggregting tensord: condensing them from multiple values down to a smaller amount of values.

In [61]:
# get the absolute values
D = tf.constant([-7,-10])
tf.abs(D) # return positive

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:

* Get the Min
* Get the Max
* Get the Mean
* Get the sum

In [62]:
# create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([41, 90, 49, 63, 58, 91,  6,  3, 34, 46, 64, 20, 71,  9, 61, 40, 56,
       16, 15, 61, 47,  2, 64, 57, 53, 46, 48, 63, 28,  8, 95, 61, 94,  4,
       72,  0, 35,  7, 28, 30, 71, 33, 90, 46,  6, 84, 81, 10,  8, 30])>

In [63]:
tf.size(E), E.shape , E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [64]:
#Find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [65]:
#Find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [66]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [67]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2195>

In [68]:
# To Find the variance of our tensor, we need access to tensor_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

ModuleNotFoundError: No module named 'tensorflow_probability'

In [69]:
#Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.084337>

### Find the positional maximum and minimum



In [72]:
#create new tensor for finding max und min
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F



<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [73]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [74]:
# Index on our largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [75]:
# Find the max value of f
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [76]:
# check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [77]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

### Squeezing a tensor (removing all single dimentions)

In [87]:
# create a tensor
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.5749372 , 0.19900596, 0.7038239 , 0.05541027, 0.5884645 ,
           0.5430788 , 0.9185413 , 0.37144518, 0.84554374, 0.9902985 ,
           0.27800095, 0.5500362 , 0.43682623, 0.68426645, 0.22095895,
           0.46595943, 0.2495377 , 0.36201143, 0.64489734, 0.02396476,
           0.6864866 , 0.11819983, 0.9782574 , 0.5938797 , 0.09975135,
           0.8805319 , 0.5449954 , 0.4293872 , 0.3130728 , 0.3187188 ,
           0.81566787, 0.41933835, 0.23228383, 0.6060114 , 0.821591  ,
           0.8203496 , 0.7298629 , 0.10527313, 0.43954647, 0.33358395,
           0.14798844, 0.2402767 , 0.23390472, 0.89162004, 0.31298292,
           0.23591721, 0.05167186, 0.2891872 , 0.7042843 , 0.3477949 ]]]]],
      dtype=float32)>

In [88]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.5749372 , 0.19900596, 0.7038239 , 0.05541027, 0.5884645 ,
       0.5430788 , 0.9185413 , 0.37144518, 0.84554374, 0.9902985 ,
       0.27800095, 0.5500362 , 0.43682623, 0.68426645, 0.22095895,
       0.46595943, 0.2495377 , 0.36201143, 0.64489734, 0.02396476,
       0.6864866 , 0.11819983, 0.9782574 , 0.5938797 , 0.09975135,
       0.8805319 , 0.5449954 , 0.4293872 , 0.3130728 , 0.3187188 ,
       0.81566787, 0.41933835, 0.23228383, 0.6060114 , 0.821591  ,
       0.8203496 , 0.7298629 , 0.10527313, 0.43954647, 0.33358395,
       0.14798844, 0.2402767 , 0.23390472, 0.89162004, 0.31298292,
       0.23591721, 0.05167186, 0.2891872 , 0.7042843 , 0.3477949 ],
      dtype=float32)>

### One-hot entcoding

In [92]:
# create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [93]:
# specify custom val for one hot encoding
tf.one_hot(some_list, depth=4, on_value='hi chuni', off_value='by chuni')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hi chuni', b'by chuni', b'by chuni', b'by chuni'],
       [b'by chuni', b'hi chuni', b'by chuni', b'by chuni'],
       [b'by chuni', b'by chuni', b'hi chuni', b'by chuni'],
       [b'by chuni', b'by chuni', b'by chuni', b'hi chuni']], dtype=object)>

### Squaring, log, sqare root

In [94]:
# create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [95]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [97]:
# find the square root
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [99]:
# find the log
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and Numpy

tensorflow interacts beautifully with Numpy arrays.

In [100]:
# Create a tensor directly
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [103]:
#convert a tensor back to a Numpy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [104]:
#convert tensor j to a Numpy array
J.numpy()

array([ 3.,  7., 10.])

In [105]:
# the default types of each arw slightly different
numpy_j = tf.constant(np.array([3.,7.,10.]))
tensor_j = tf.constant([3.,7.,10.])
# check the datatypes of each
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

### finding access to GPUs

In [108]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]